// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://puuzmlhoepqotgzlpdho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1dXptbGhvZXBxb3RnemxwZGhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNTgwNjUsImV4cCI6MjA2NjczNDA2NX0.PkopYEQigmHUduntgPFUVWUPnqjX0HnFNil_j0W0-2g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);